name: 'ecommerce_dbt'
version: '1.0'
config-version: 2

profile: 'ecommerce_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  ecommerce_dbt:
    staging:
      +materialized: table
    marts:
      +materialized: table
seeds:
  ecommerce_dbt:
    +engine: MergeTree()
    +order_by: Order_ID